version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws/aws-sdk-php
    versions:
    - 3.172.3
    - 3.172.4
    - 3.173.0
    - 3.173.10
    - 3.173.11
    - 3.173.12
    - 3.173.13
    - 3.173.14
    - 3.173.15
    - 3.173.16
    - 3.173.17
    - 3.173.18
    - 3.173.2
    - 3.173.3
    - 3.173.4
    - 3.173.5
    - 3.173.6
    - 3.173.7
    - 3.173.8
    - 3.173.9
  - dependency-name: mockery/mockery
    versions:
    - 1.3.3
